sonar.projectKey=devops-cicd-security-platform
sonar.projectName=DevOps CI/CD Security Platform
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.inclusions=**/*.yaml,**/*.yml,**/*.sh,**/*.py,**/*.java

sonar.qualitygate.wait=true
